"""add campaign_stats table

Revision ID: 03f96c0e6866
Revises: d77508c6a7df
Create Date: 2026-01-21 11:36:44.142329

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03f96c0e6866'
down_revision = 'd77508c6a7df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campaign_stats',
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('total_targets', sa.Integer(), nullable=False),
    sa.Column('sent_count', sa.Integer(), nullable=False),
    sa.Column('opened_count', sa.Integer(), nullable=False),
    sa.Column('clicked_count', sa.Integer(), nullable=False),
    sa.Column('submitted_count', sa.Integer(), nullable=False),
    sa.Column('reported_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('campaign_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('campaign_stats')
    # ### end Alembic commands ###
